/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AgentSignupRouteImport } from './routes/agent-signup'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreAgentIdRouteImport } from './routes/store.$agentId'
import { Route as AgentSubAgentsRouteImport } from './routes/agent.sub-agents'
import { Route as AgentStoreRouteImport } from './routes/agent.store'
import { Route as AgentSettingsRouteImport } from './routes/agent.settings'
import { Route as AgentOrdersRouteImport } from './routes/agent.orders'
import { Route as AgentEarningsRouteImport } from './routes/agent.earnings'
import { Route as AgentCustomersRouteImport } from './routes/agent.customers'
import { Route as AgentBuyRouteImport } from './routes/agent.buy'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPricesRouteImport } from './routes/admin.prices'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'

const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSignupRoute = AgentSignupRouteImport.update({
  id: '/agent-signup',
  path: '/agent-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreAgentIdRoute = StoreAgentIdRouteImport.update({
  id: '/store/$agentId',
  path: '/store/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSubAgentsRoute = AgentSubAgentsRouteImport.update({
  id: '/sub-agents',
  path: '/sub-agents',
  getParentRoute: () => AgentRoute,
} as any)
const AgentStoreRoute = AgentStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSettingsRoute = AgentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AgentRoute,
} as any)
const AgentOrdersRoute = AgentOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AgentRoute,
} as any)
const AgentEarningsRoute = AgentEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AgentRoute,
} as any)
const AgentCustomersRoute = AgentCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AgentRoute,
} as any)
const AgentBuyRoute = AgentBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AgentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricesRoute = AdminPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/agent-signup': typeof AgentSignupRoute
  '/buy': typeof BuyRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prices': typeof AdminPricesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/buy': typeof AgentBuyRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/earnings': typeof AgentEarningsRoute
  '/agent/orders': typeof AgentOrdersRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/agent/store': typeof AgentStoreRoute
  '/agent/sub-agents': typeof AgentSubAgentsRoute
  '/store/$agentId': typeof StoreAgentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-signup': typeof AgentSignupRoute
  '/buy': typeof BuyRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prices': typeof AdminPricesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/buy': typeof AgentBuyRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/earnings': typeof AgentEarningsRoute
  '/agent/orders': typeof AgentOrdersRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/agent/store': typeof AgentStoreRoute
  '/agent/sub-agents': typeof AgentSubAgentsRoute
  '/store/$agentId': typeof StoreAgentIdRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/agent-signup': typeof AgentSignupRoute
  '/buy': typeof BuyRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prices': typeof AdminPricesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/buy': typeof AgentBuyRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/earnings': typeof AgentEarningsRoute
  '/agent/orders': typeof AgentOrdersRoute
  '/agent/settings': typeof AgentSettingsRoute
  '/agent/store': typeof AgentStoreRoute
  '/agent/sub-agents': typeof AgentSubAgentsRoute
  '/store/$agentId': typeof StoreAgentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/agent-signup'
    | '/buy'
    | '/admin/agents'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/prices'
    | '/admin/settings'
    | '/admin/users'
    | '/agent/buy'
    | '/agent/customers'
    | '/agent/earnings'
    | '/agent/orders'
    | '/agent/settings'
    | '/agent/store'
    | '/agent/sub-agents'
    | '/store/$agentId'
    | '/admin/'
    | '/agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-signup'
    | '/buy'
    | '/admin/agents'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/prices'
    | '/admin/settings'
    | '/admin/users'
    | '/agent/buy'
    | '/agent/customers'
    | '/agent/earnings'
    | '/agent/orders'
    | '/agent/settings'
    | '/agent/store'
    | '/agent/sub-agents'
    | '/store/$agentId'
    | '/admin'
    | '/agent'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/agent-signup'
    | '/buy'
    | '/admin/agents'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/prices'
    | '/admin/settings'
    | '/admin/users'
    | '/agent/buy'
    | '/agent/customers'
    | '/agent/earnings'
    | '/agent/orders'
    | '/agent/settings'
    | '/agent/store'
    | '/agent/sub-agents'
    | '/store/$agentId'
    | '/admin/'
    | '/agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  AgentSignupRoute: typeof AgentSignupRoute
  BuyRoute: typeof BuyRoute
  StoreAgentIdRoute: typeof StoreAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-signup': {
      id: '/agent-signup'
      path: '/agent-signup'
      fullPath: '/agent-signup'
      preLoaderRoute: typeof AgentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/$agentId': {
      id: '/store/$agentId'
      path: '/store/$agentId'
      fullPath: '/store/$agentId'
      preLoaderRoute: typeof StoreAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/sub-agents': {
      id: '/agent/sub-agents'
      path: '/sub-agents'
      fullPath: '/agent/sub-agents'
      preLoaderRoute: typeof AgentSubAgentsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/store': {
      id: '/agent/store'
      path: '/store'
      fullPath: '/agent/store'
      preLoaderRoute: typeof AgentStoreRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/settings': {
      id: '/agent/settings'
      path: '/settings'
      fullPath: '/agent/settings'
      preLoaderRoute: typeof AgentSettingsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/orders': {
      id: '/agent/orders'
      path: '/orders'
      fullPath: '/agent/orders'
      preLoaderRoute: typeof AgentOrdersRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/earnings': {
      id: '/agent/earnings'
      path: '/earnings'
      fullPath: '/agent/earnings'
      preLoaderRoute: typeof AgentEarningsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/customers': {
      id: '/agent/customers'
      path: '/customers'
      fullPath: '/agent/customers'
      preLoaderRoute: typeof AgentCustomersRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/buy': {
      id: '/agent/buy'
      path: '/buy'
      fullPath: '/agent/buy'
      preLoaderRoute: typeof AgentBuyRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prices': {
      id: '/admin/prices'
      path: '/prices'
      fullPath: '/admin/prices'
      preLoaderRoute: typeof AdminPricesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPricesRoute: typeof AdminPricesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPricesRoute: AdminPricesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentBuyRoute: typeof AgentBuyRoute
  AgentCustomersRoute: typeof AgentCustomersRoute
  AgentEarningsRoute: typeof AgentEarningsRoute
  AgentOrdersRoute: typeof AgentOrdersRoute
  AgentSettingsRoute: typeof AgentSettingsRoute
  AgentStoreRoute: typeof AgentStoreRoute
  AgentSubAgentsRoute: typeof AgentSubAgentsRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentBuyRoute: AgentBuyRoute,
  AgentCustomersRoute: AgentCustomersRoute,
  AgentEarningsRoute: AgentEarningsRoute,
  AgentOrdersRoute: AgentOrdersRoute,
  AgentSettingsRoute: AgentSettingsRoute,
  AgentStoreRoute: AgentStoreRoute,
  AgentSubAgentsRoute: AgentSubAgentsRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  AgentSignupRoute: AgentSignupRoute,
  BuyRoute: BuyRoute,
  StoreAgentIdRoute: StoreAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
